In [1]:
import pandas as pd
import glob
import re

In [2]:
final_df = None
experiments_names = []

for filename in glob.glob(r"results/*"):
    df = pd.read_csv(filename)
    df = df.set_index([df.columns[0], df.columns[1]])
    
    horizons = []
    experiment_name = "".join(df.columns[0].split("_")[:-1])
    experiments_names.append(experiment_name)
    [horizons.append(x.split("_")[-1]) for x in df.columns]
    
    # print(horizons)
    # print(experiment_name)
    
    df.columns = pd.MultiIndex.from_product(([experiment_name], horizons))
    
    
    if final_df is None:
        final_df = df
    else:
        final_df = pd.concat([final_df, df], axis=1)

In [3]:
final_df

                      AirlinePassengers                 Electricity311         \
                                      1       3       6              1      3
Model          Metric
PINPOINT_1CONV MAE                29.76   33.85   19.33           4.62   5.15
               RMSE               37.21   42.70   23.08           6.82   7.45
PINPOINT_2CONV MAE                65.83   84.66  103.72           5.35   6.49
               RMSE               89.54  111.88  146.72           7.84   9.17
Prophet        MAE                33.57   34.31   32.25           6.61   6.77
               RMSE               41.29   42.08   40.72           9.01   9.15
ARIMA          MAE                43.55   40.17   43.86           5.42   5.58
               RMSE               51.01   50.05   55.11           8.26   8.21
ARIMA_PP       MAE                42.39   38.89   43.92           5.44   5.59
               RMSE               50.09   48.81   54.48           8.28   8.23
Naive          MAE                45.10   53.80   68.13           5.87   6.92
               RMSE               52.61   62.78   78.24           9.05  10.01

                            Electricity132                 Milk                \
                          7              1      3      7      1      3      6
Model          Metric
PINPOINT_1CONV MAE     5.79           2.80   2.83   2.79   9.39  12.52  11.95
               RMSE    8.06           4.54   4.60   4.60  11.36  14.17  14.70
PINPOINT_2CONV MAE     6.35           2.78   2.80   2.81  11.21  15.13  13.38
               RMSE    9.07           4.60   4.64   4.66  14.02  18.28  17.24
Prophet        MAE     7.07           3.43   3.45   3.45   9.23   9.36   9.53
               RMSE    9.42           5.09   5.11   5.12  11.88  12.15  12.60
ARIMA          MAE     5.44           6.29   5.95   6.85  53.70  41.60  42.13
               RMSE    7.84           7.62   7.33   8.11  66.20  58.11  55.36
ARIMA_PP       MAE     5.44           6.35   5.94   6.84  60.17  37.43  40.47
               RMSE    7.84           7.67   7.31   8.10  70.00  53.00  53.58
Naive          MAE     7.09           6.69   9.38   7.40  39.12  69.50  80.06
               RMSE    9.87          10.34  12.63  11.03  46.05  81.57  92.12

                      Electricity239             Covid-19 Cases           \
                                   1     3     7              1        3
Model          Metric
PINPOINT_1CONV MAE              3.72  4.56  5.74         773.15   932.87
               RMSE             5.69  6.57  8.05        1149.80  1415.11
PINPOINT_2CONV MAE              3.92  4.83  5.67         992.59  1041.97
               RMSE             6.04  6.89  7.93        1443.93  1541.27
Prophet        MAE              5.69  5.81  5.98        4360.67  4485.61
               RMSE             7.61  7.74  7.93        5002.66  5135.11
ARIMA          MAE              3.75  4.48  5.12        1530.17  1636.44
               RMSE             5.93  6.68  7.40        2167.02  2643.37
ARIMA_PP       MAE              3.75  4.49  5.12        1533.72  1824.21
               RMSE             5.93  6.69  7.40        2173.07  2786.94
Naive          MAE              3.84  4.67  5.80        1370.91  2044.20
               RMSE             6.11  6.76  8.22        1991.70  3121.98


                             7
Model          Metric
PINPOINT_1CONV MAE     3102.04
               RMSE    3893.59
PINPOINT_2CONV MAE     1485.33
               RMSE    2083.94
Prophet        MAE     4719.83
               RMSE    5397.43
ARIMA          MAE     1252.83
               RMSE    1808.57
ARIMA_PP       MAE     1521.69
               RMSE    2222.14
Naive          MAE     1725.68
               RMSE    2652.60

In [4]:
order = [('Covid-19 Cases', '1'),
         ('Covid-19 Cases', '3'),
         ('Covid-19 Cases', '7'),
         ('Milk', '1'),
         ('Milk', '3'),
         ('Milk', '6'),
         ('AirlinePassengers', '1'),
         ('AirlinePassengers', '3'),
         ('AirlinePassengers', '6'),
         ('Electricity132', '1'),
         ('Electricity132', '3'),
         ('Electricity132', '7'),
         ('Electricity239', '1'),
         ('Electricity239', '3'),
         ('Electricity239', '7'),
         ('Electricity311', '1'),
         ('Electricity311', '3'),
         ('Electricity311', '7')]

In [5]:
final_df = final_df[order]

In [6]:
final_df

                      Covid-19 Cases                     Milk                \
                                   1        3        7      1      3      6
Model          Metric
PINPOINT_1CONV MAE            773.15   932.87  3102.04   9.39  12.52  11.95
               RMSE          1149.80  1415.11  3893.59  11.36  14.17  14.70
PINPOINT_2CONV MAE            992.59  1041.97  1485.33  11.21  15.13  13.38
               RMSE          1443.93  1541.27  2083.94  14.02  18.28  17.24
Prophet        MAE           4360.67  4485.61  4719.83   9.23   9.36   9.53
               RMSE          5002.66  5135.11  5397.43  11.88  12.15  12.60
ARIMA          MAE           1530.17  1636.44  1252.83  53.70  41.60  42.13
               RMSE          2167.02  2643.37  1808.57  66.20  58.11  55.36
ARIMA_PP       MAE           1533.72  1824.21  1521.69  60.17  37.43  40.47
               RMSE          2173.07  2786.94  2222.14  70.00  53.00  53.58
Naive          MAE           1370.91  2044.20  1725.68  39.12  69.50  80.06
               RMSE          1991.70  3121.98  2652.60  46.05  81.57  92.12

                      AirlinePassengers                 Electricity132         \
                                      1       3       6              1      3
Model          Metric
PINPOINT_1CONV MAE                29.76   33.85   19.33           2.80   2.83
               RMSE               37.21   42.70   23.08           4.54   4.60
PINPOINT_2CONV MAE                65.83   84.66  103.72           2.78   2.80
               RMSE               89.54  111.88  146.72           4.60   4.64
Prophet        MAE                33.57   34.31   32.25           3.43   3.45
               RMSE               41.29   42.08   40.72           5.09   5.11
ARIMA          MAE                43.55   40.17   43.86           6.29   5.95
               RMSE               51.01   50.05   55.11           7.62   7.33
ARIMA_PP       MAE                42.39   38.89   43.92           6.35   5.94
               RMSE               50.09   48.81   54.48           7.67   7.31
Naive          MAE                45.10   53.80   68.13           6.69   9.38
               RMSE               52.61   62.78   78.24          10.34  12.63

                             Electricity239             Electricity311         \
                           7              1     3     7              1      3
Model          Metric
PINPOINT_1CONV MAE      2.79           3.72  4.56  5.74           4.62   5.15
               RMSE     4.60           5.69  6.57  8.05           6.82   7.45
PINPOINT_2CONV MAE      2.81           3.92  4.83  5.67           5.35   6.49
               RMSE     4.66           6.04  6.89  7.93           7.84   9.17
Prophet        MAE      3.45           5.69  5.81  5.98           6.61   6.77
               RMSE     5.12           7.61  7.74  7.93           9.01   9.15
ARIMA          MAE      6.85           3.75  4.48  5.12           5.42   5.58
               RMSE     8.11           5.93  6.68  7.40           8.26   8.21
ARIMA_PP       MAE      6.84           3.75  4.49  5.12           5.44   5.59
               RMSE     8.10           5.93  6.69  7.40           8.28   8.23
Naive          MAE      7.40           3.84  4.67  5.80           5.87   6.92
               RMSE    11.03           6.11  6.76  8.22           9.05  10.01


                          7
Model          Metric
PINPOINT_1CONV MAE     5.79
               RMSE    8.06
PINPOINT_2CONV MAE     6.35
               RMSE    9.07
Prophet        MAE     7.07
               RMSE    9.42
ARIMA          MAE     5.44
               RMSE    7.84
ARIMA_PP       MAE     5.44
               RMSE    7.84
Naive          MAE     7.09
               RMSE    9.87

In [7]:
final_df.to_csv("final_results.csv", float_format='%.2f')

In [8]:
for e in experiments_names:
    df = final_df.loc[final_df.index.get_level_values('Metric') == 'MAE']
    df.index = df.index.droplevel(1)
    df = df.loc[:, df.columns.get_level_values(0) == e]
    df.columns = df.columns.droplevel(0)
    
    for h in df.columns:
        best = df.loc[df.loc[:, h] == min(df.loc[:, h])]
        print(f"{e}, {h}: {best.index[0]}")

AirlinePassengers, 1: PINPOINT_1CONV
AirlinePassengers, 3: PINPOINT_1CONV
AirlinePassengers, 6: PINPOINT_1CONV
Electricity311, 1: PINPOINT_1CONV
Electricity311, 3: PINPOINT_1CONV
Electricity311, 7: ARIMA
Electricity132, 1: PINPOINT_2CONV
Electricity132, 3: PINPOINT_2CONV
Electricity132, 7: PINPOINT_1CONV
Milk, 1: Prophet
Milk, 3: Prophet
Milk, 6: Prophet
Electricity239, 1: PINPOINT_1CONV
Electricity239, 3: ARIMA
Electricity239, 7: ARIMA
Covid-19 Cases, 1: PINPOINT_1CONV
Covid-19 Cases, 3: PINPOINT_1CONV
Covid-19 Cases, 7: ARIMA